import bisect
import hmac
import logging
import os
import time
from dataclasses import dataclass
from threading import Lock
from typing import Dict, List, Optional, Tuple

from fastapi import FastAPI, Header, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field


def _parse_api_keys() -> Tuple[str, ...]:
    keys_csv = os.getenv("MT5_API_KEYS", "")
    keys = [item.strip() for item in keys_csv.split(",") if item.strip()]
    single_key = os.getenv("MT5_API_KEY", "your-secret-key").strip()
    if single_key and single_key not in keys:
        keys.append(single_key)
    return tuple(keys)


def _parse_int_env(name: str, default: int) -> int:
    raw = os.getenv(name, str(default)).strip()
    try:
        return int(raw)
    except ValueError:
        return default


def _parse_bool_env(name: str, default: bool) -> bool:
    raw = os.getenv(name, "1" if default else "0").strip().lower()
    return raw in {"1", "true", "yes", "on"}


class AppConfig(BaseModel):
    model_config = ConfigDict(frozen=True)

    api_keys: Tuple[str, ...]
    max_ts_drift_sec: int
    log_heartbeats: bool


CONFIG = AppConfig(
    api_keys=_parse_api_keys(),
    max_ts_drift_sec=max(0, _parse_int_env("MT5_MAX_TS_DRIFT_SEC", 300)),
    log_heartbeats=_parse_bool_env("MT5_LOG_HEARTBEAT", True),
)

logger = logging.getLogger("mt5_heartbeat")
if not logger.handlers:
    logging.basicConfig(level=logging.INFO)

app = FastAPI(title="MT5 Heartbeat API", version="2.0.0")

STARTED_MONOTONIC = time.monotonic()
_latest_heartbeats: Dict[str, "StoredHeartbeatRecord"] = {}
_sorted_terminal_ids: List[str] = []
_store_lock = Lock()


@dataclass(slots=True)
class StoredHeartbeatRecord:
    received_at: int
    payload: "HeartbeatPayload"


class HeartbeatPayload(BaseModel):
    model_config = ConfigDict(extra="ignore")

    login: int = Field(description="MT5 account login ID")
    server: str = Field(min_length=1, max_length=128)
    terminal_id: str = Field(min_length=1, max_length=128)
    terminal_active: bool
    algo_active: bool
    ts: int = Field(description="Unix timestamp generated by MT5")
    account_name: Optional[str] = Field(default=None, max_length=256)
    latency_ms: Optional[int] = Field(default=None, ge=0)
    trades_last_3d: Optional[int] = Field(default=None, ge=0)
    volume_last_3d: Optional[float] = None
    profit_last_3d: Optional[float] = None
    trades_last_7d: Optional[int] = Field(default=None, ge=0)
    volume_last_7d: Optional[float] = None
    profit_last_7d: Optional[float] = None
    connected: Optional[bool] = None
    build: Optional[int] = Field(default=None, ge=0)
    balance: Optional[float] = None
    equity: Optional[float] = None
    margin: Optional[float] = None
    free_margin: Optional[float] = None
    margin_level: Optional[float] = None
    positions_total: Optional[int] = Field(default=None, ge=0)
    orders_total: Optional[int] = Field(default=None, ge=0)
    floating_pl: Optional[float] = None
    last_error: Optional[int] = None


class HeartbeatAck(BaseModel):
    ok: bool
    received_at: int
    terminal_id: str


class StoredHeartbeat(BaseModel):
    received_at: int
    payload: HeartbeatPayload


class HealthResponse(BaseModel):
    ok: bool
    uptime_sec: int
    tracked_terminals: int
    max_ts_drift_sec: int


def _is_authorized(x_api_key: Optional[str]) -> bool:
    if not x_api_key:
        return False
    for key in CONFIG.api_keys:
        if hmac.compare_digest(x_api_key, key):
            return True
    return False


def _validate_timestamp(ts: int, now: int) -> None:
    if abs(now - ts) > CONFIG.max_ts_drift_sec:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "Timestamp drift exceeds MT5_MAX_TS_DRIFT_SEC "
                f"({CONFIG.max_ts_drift_sec}s)"
            ),
        )


@app.get("/health", response_model=HealthResponse)
def health() -> HealthResponse:
    with _store_lock:
        tracked = len(_latest_heartbeats)
    return HealthResponse.model_construct(
        ok=True,
        uptime_sec=max(0, int(time.monotonic() - STARTED_MONOTONIC)),
        tracked_terminals=tracked,
        max_ts_drift_sec=CONFIG.max_ts_drift_sec,
    )


@app.get("/mt5/heartbeat/latest/{terminal_id}", response_model=StoredHeartbeat)
def get_latest_heartbeat(terminal_id: str) -> StoredHeartbeat:
    with _store_lock:
        latest = _latest_heartbeats.get(terminal_id)
    if latest is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No heartbeat found for terminal_id={terminal_id}",
        )
    return StoredHeartbeat.model_construct(received_at=latest.received_at, payload=latest.payload)


@app.get("/mt5/heartbeat/terminals", response_model=List[str])
def list_terminals() -> List[str]:
    with _store_lock:
        terminal_ids = _sorted_terminal_ids.copy()
    return terminal_ids


@app.post("/mt5/heartbeat", response_model=HeartbeatAck)
def mt5_heartbeat(
    payload: HeartbeatPayload,
    x_api_key: Optional[str] = Header(default=None, alias="X-API-Key"),
) -> HeartbeatAck:
    if not _is_authorized(x_api_key):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key",
        )

    received_at = int(time.time())
    _validate_timestamp(payload.ts, received_at)
    stored = StoredHeartbeatRecord(received_at=received_at, payload=payload)

    with _store_lock:
        if payload.terminal_id not in _latest_heartbeats:
            bisect.insort(_sorted_terminal_ids, payload.terminal_id)
        _latest_heartbeats[payload.terminal_id] = stored

    if CONFIG.log_heartbeats:
        logger.info(
            "Heartbeat received terminal_id=%s login=%s server=%s algo_active=%s last_error=%s",
            payload.terminal_id,
            payload.login,
            payload.server,
            payload.algo_active,
            payload.last_error,
        )

    return HeartbeatAck.model_construct(
        ok=True,
        received_at=received_at,
        terminal_id=payload.terminal_id,
    )
